
package edu.uci.ics.perpetual.parser;

import edu.uci.ics.perpetual.JSQLParserException;
import edu.uci.ics.perpetual.statement.Statement;

import java.io.Reader;

/**
 * A JSqlParser implementation that uses a parser generated by JavaCC
 */
public class CCJSqlParserManager implements JSqlParser {

    @Override
    public Statement parse(Reader statementReader) throws JSQLParserException {
        CCJSqlParser parser = new CCJSqlParser(new StreamProvider(statementReader));
        try {
            return parser.Statement();
        } catch (Exception ex) {
            throw new JSQLParserException(ex);
        }
    }

    @Override
    public Statement parse(String query) throws JSQLParserException, ParseException {
        CCJSqlParser parser = new CCJSqlParser(query);
        try {
            return parser.Statement();
        } catch (Exception ex) {
            throw new JSQLParserException(ex);
        }
    }

}
